# Generated by Django 4.2.28 on 2026-02-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_room_description_room_floor_room_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AlterField(
            model_name='allocation',
            name='allocated_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='register_no',
            field=models.CharField(max_length=20),
        ),
    ]
