# Generated by Django 4.2.28 on 2026-02-15 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='allocated_on',
            new_name='allocated_date',
        ),
    ]
