# Generated by Django 4.2.28 on 2026-02-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_rename_allocated_on_allocation_allocated_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
