# Generated by Django 4.2.28 on 2026-02-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_delete_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
