# Generated by Django 4.2.28 on 2026-02-26 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_studentprofile_address_studentprofile_parent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='block',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.room'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='hostel.studentprofile'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='hostel.studentprofile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='register_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
