# Generated by Django 4.2.29 on 2026-03-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_room_block_alter_allocation_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='FullName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
