# Generated by Django 4.2.29 on 2026-03-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_studentprofile_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='FullName',
            new_name='full_name',
        ),
    ]
