# Generated by Django 4.2.29 on 2026-03-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_rename_fullname_studentprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
    ]
