# Generated by Django 4.2.29 on 2026-03-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_remove_room_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
