# Generated by Django 4.2.29 on 2026-03-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_alter_studentprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
    ]
