# Generated by Django 4.2.29 on 2026-03-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0017_remove_studentprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('2 Sharing', '2 Sharing'), ('4 Sharing', '4 Sharing'), ('6 Sharing', '6 Sharing')], default='2 Sharing', max_length=20),
        ),
    ]
