# Generated by Django 4.2.29 on 2026-03-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0018_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='room_preference',
            field=models.CharField(blank=True, choices=[('2 Sharing', '2 Sharing'), ('4 Sharing', '4 Sharing'), ('6 Sharing', '6 Sharing')], max_length=20, null=True),
        ),
    ]
