# Generated by Django 4.2.29 on 2026-03-18 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0019_studentprofile_room_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='allocated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
