# Generated by Django 4.2.29 on 2026-03-19 03:25

from django.db import migrations, models
import hostel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0020_alter_allocation_allocated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='due_date',
            field=models.DateField(default=hostel.models.get_month_end),
        ),
    ]
